name: PHP SDK CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['7.2', '7.4']
    name: run tests @${{ matrix.php }}
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          version: "2.2"
      - run: "composer unit-test"
      - run: "composer quality-check"
